name: Deploy deeplinks app
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'postgresql/**'
  workflow_dispatch:
defaults:
  run:
    working-directory: ./
env:
  MIGRATIONS_ID_TYPE_SQL: bigint
  MIGRATIONS_HASURA_PATH: localhost:8080
  MIGRATIONS_HASURA_SSL: 0
  MIGRATIONS_HASURA_SECRET: myadminsecretkey
  MIGRATIONS_DEEPLINKS_URL: http://host.docker.internal:3006
  JWT_SECRET: '{"type":"HS256","key":"3EK6FD+o0+c7tzBNVfjpMkNDi2yARAAKzQlk8O2IKoxQu4nF7EdAh8s3TwpHwrdWT6R"}'
jobs:
  dockerize:
    name: dockerize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.20'
      - name: ci
        run: npm ci
      - name: build
        run: npm run package:build
      - name: docker-ver backup dir
        run: mkdir backup
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: deepf/deeplinks
      - name: build docker image for 
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: docker init
        run: cd local/actions && docker-compose -p deep up -d
      - name: docker logs deep-links
        run: docker logs deep-links
      - name: migrate
        run: npm run migrate
      - name: snapshot:create
        run: 'npm run snapshot:create'
      - name: docker-ver backup volume
        run: docker run --rm --volumes-from deep-postgres -v $(pwd):/temp ubuntu tar -c -v -C /var/lib/postgresql -f /temp/backup/volume.tar ./data
      - name: docker-ver backup migrations log
        run: cp .migrate backup/.migrate
      - name: Extract metadata (tags, labels) for Docker
        id: meta_push
        uses: docker/metadata-action@v3
        with:
          images: deepf/deeplinks
      - name: build docker image and push
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta_push.outputs.tags }}
          labels: ${{ steps.meta_push.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build_push.outputs.digest }}
